import { createFileRoute } from "@tanstack/react-router";
import { PageHeader, Section } from "../components/site/PageHeader";
import { seoUrls } from "../lib/site-url";

export const Route = createFileRoute("/terms")({
  head: () => {
    const urls = seoUrls("/terms");
    return {
      meta: [
        { title: "Terms of Service — Gita Strategy" },
        {
          name: "description",
          content:
            "The terms that govern use of the Gita Strategy website, its educational content, newsletter and AI assistant.",
        },
        { property: "og:title", content: "Terms of Service — Gita Strategy" },
        {
          property: "og:description",
          content: "Acceptable use, intellectual property, disclaimers and liability for Gita Strategy.",
        },
        { property: "og:type", content: "website" },
        ...urls.meta,
      ],
      links: urls.links,
    };
  },
  component: TermsPage,
});

const sections = [
  {
    title: "1. Acceptance",
    body: "By using gitastrategy.in you agree to these terms. If you do not agree, please stop using the site.",
  },
  {
    title: "2. Educational purpose only",
    body: "All verses, frameworks, case studies and assistant replies are published for study and reflection. They are not legal, financial, medical or professional advice, and no outcome is guaranteed. Always apply your own judgement and, where relevant, consult a qualified professional.",
  },
  {
    title: "3. AI assistant",
    body: "The Gita Strategy Assistant is generated by an AI model. It can be wrong, incomplete or out of date, and it may paraphrase scripture. Verify any verse reference before quoting it publicly. Do not submit confidential, personal or sensitive information to the assistant.",
  },
  {
    title: "4. Intellectual property",
    body: "Original commentary, frameworks, case studies and design on this site belong to Gita Strategy. You may quote short extracts with clear attribution and a link back. Republishing whole articles, or using the content to train commercial models, requires written permission. Bhagavad Gita verses themselves are in the public domain; our translations and interpretations are not.",
  },
  {
    title: "5. Acceptable use",
    body: "Do not attempt to disrupt the site, scrape it at volume, submit automated form entries, upload malicious content, or use the assistant to generate unlawful, hateful or misleading material. We may block access that breaches these rules.",
  },
  {
    title: "6. Third-party links",
    body: "We link to LinkedIn, external research and other sites for reference. We do not control them and are not responsible for their content or privacy practices.",
  },
  {
    title: "7. Availability",
    body: "The site is provided 'as is'. We aim for continuous availability but do not guarantee uninterrupted or error-free service, and we may change or withdraw features at any time.",
  },
  {
    title: "8. Liability",
    body: "To the maximum extent permitted by law, Gita Strategy is not liable for indirect or consequential loss arising from use of this site or reliance on its content.",
  },
  {
    title: "9. Governing law",
    body: "These terms are governed by the laws of India, with jurisdiction in the courts of Mumbai, Maharashtra.",
  },
  {
    title: "10. Contact",
    body: "Questions about these terms: gitastrategy@gmail.com.",
  },
];

function TermsPage() {
  return (
    <>
      <PageHeader
        eyebrow="Legal"
        title="Terms of Service"
        intro="The ground rules for using Gita Strategy's content, newsletter and assistant."
      />
      <Section className="max-w-3xl">
        <p className="text-sm text-muted-foreground">Last updated: 1 January 2026</p>
        <div className="mt-10 space-y-8">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="font-display text-xl font-semibold">{s.title}</h2>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.body}</p>
            </div>
          ))}
        </div>
      </Section>
    </>
  );
}
