// Syncs site content from public Google Sheets (or CSV URLs) into src/data/*.ts
// so articles and verses can be updated without editing source files.
//
//   bun run sync            # sync everything that is configured
//
// Configuration (env vars, all optional — sensible defaults below):
//   ARTICLES_SHEET_ID / ARTICLES_GID / ARTICLES_CSV_URL
//   VERSES_SHEET_ID   / VERSES_GID   / VERSES_CSV_URL
//
// Verses sheet columns: Id, Reference, Sanskrit, Translation, Framework,
//                       Mapping, Example, Takeaway
// Articles sheet columns: PostId, Date, Title, Category, SubCategory, Topic,
//                       Trend, Summary, Content, ImageUrl, LinkedInPostURN
import { writeFileSync } from "node:fs";

// Treat blank/whitespace env vars (common with unset GitHub Actions vars) as unset.
const env = (name) => {
  const v = (process.env[name] ?? "").trim();
  return v || undefined;
};

const ARTICLES_SHEET_ID =
  env("ARTICLES_SHEET_ID") ?? "1bYXRX8aThHDZdj0kslXDK-EdzR2-KjXJq4c880Q6Pkg";
const ARTICLES_GID = env("ARTICLES_GID") ?? "0";
const VERSES_SHEET_ID = env("VERSES_SHEET_ID") ?? "";
const VERSES_GID = env("VERSES_GID") ?? "0";

const sheetCsvUrl = (id, gid) =>
  `https://docs.google.com/spreadsheets/d/${id}/gviz/tq?tqx=out:csv&gid=${gid}`;

function parseCsv(text) {
  const rows = [];
  let row = [],
    field = "",
    quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else quoted = false;
      } else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else if (c !== "\r") field += c;
  }
  if (field || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

async function fetchRows(url) {
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`Sheet fetch failed (${res.status}) for ${url}`);
  const rows = parseCsv(await res.text()).filter((r) => r.some((c) => c.trim()));
  if (!rows.length) throw new Error(`Sheet returned no rows: ${url}`);
  const header = rows.shift().map((h) => h.trim());
  return rows.map((r) => {
    const o = {};
    header.forEach((h, i) => (o[h] = (r[i] ?? "").trim()));
    return o;
  });
}

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);

const pick = (row, ...names) => {
  for (const n of names) if (row[n]) return row[n];
  return "";
};

async function syncArticles() {
  const url = process.env.ARTICLES_CSV_URL || sheetCsvUrl(ARTICLES_SHEET_ID, ARTICLES_GID);
  const rows = (await fetchRows(url)).filter((r) => pick(r, "Title"));
  const posts = rows.map((r) => {
    const title = pick(r, "Title");
    return {
      id: pick(r, "PostId", "Id") || slugify(title),
      slug: slugify(title),
      date: pick(r, "Date"),
      title,
      category: pick(r, "Category"),
      subCategory: pick(r, "SubCategory", "Sub Category"),
      topic: pick(r, "Topic"),
      trend: pick(r, "Trend"),
      summary: pick(r, "Summary"),
      content: pick(r, "Content", "Article", "Body"),
      imageUrl: pick(r, "ImageUrl", "Image"),
      urn: pick(r, "LinkedInPostURN", "URN"),
    };
  });

  const seen = new Set();
  for (const p of posts) {
    let s = p.slug || "post",
      n = 2;
    while (seen.has(s)) s = `${p.slug}-${n++}`;
    seen.add(s);
    p.slug = s;
  }

  const body = `// AUTO-GENERATED by scripts/sync-content.mjs — do not edit by hand.
// Source: ${url}

export type LinkedInPost = {
  id: string;
  slug: string;
  date: string;
  title: string;
  category: string;
  subCategory: string;
  topic: string;
  trend: string;
  summary: string;
  content: string;
  imageUrl: string;
  urn: string;
};

export const linkedInPosts: LinkedInPost[] = ${JSON.stringify(posts, null, 2)};

export function sortedLinkedInPosts(): LinkedInPost[] {
  const time = (d: string) => {
    const t = Date.parse(d.replace(/-/g, " "));
    return Number.isNaN(t) ? 0 : t;
  };
  return [...linkedInPosts].sort((a, b) => time(b.date) - time(a.date));
}

export function findLinkedInPost(slug: string): LinkedInPost | undefined {
  return linkedInPosts.find((p) => p.slug === slug);
}
`;
  writeFileSync(new URL("../src/data/linkedin-posts.ts", import.meta.url), body);
  console.log(`articles: wrote ${posts.length} posts`);
}

async function syncVerses() {
  if (!process.env.VERSES_CSV_URL && !VERSES_SHEET_ID) {
    console.log("verses: skipped (set VERSES_SHEET_ID or VERSES_CSV_URL to enable)");
    return;
  }
  const url = process.env.VERSES_CSV_URL || sheetCsvUrl(VERSES_SHEET_ID, VERSES_GID);
  const rows = (await fetchRows(url)).filter(
    (r) => pick(r, "Translation") && pick(r, "Reference", "Ref"),
  );
  const verses = rows.map((r) => ({
    id: pick(r, "Id", "ID") || slugify(pick(r, "Reference", "Ref")),
    ref: pick(r, "Reference", "Ref"),
    sanskrit: pick(r, "Sanskrit", "Shloka"),
    translation: pick(r, "Translation"),
    framework: pick(r, "Framework"),
    mapping: pick(r, "Mapping", "Strategy Mapping"),
    example: pick(r, "Example"),
    takeaway: pick(r, "Takeaway"),
  }));

  const body = `// AUTO-GENERATED by scripts/sync-content.mjs — do not edit by hand.
// Source: ${url}
// Empty array means "no sheet configured"; src/data/gita.ts then uses its built-in verses.
import type { Verse } from "./gita";

export const syncedVerses: Verse[] = ${JSON.stringify(verses, null, 2)};
`;
  writeFileSync(new URL("../src/data/verses-generated.ts", import.meta.url), body);
  console.log(`verses: wrote ${verses.length} verses`);
}

const tasks = [
  ["articles", syncArticles],
  ["verses", syncVerses],
];
let failed = false;
for (const [name, run] of tasks) {
  try {
    await run();
  } catch (err) {
    failed = true;
    console.error(`${name}: sync failed — keeping existing data.\n  ${err.message}`);
  }
}
process.exit(failed ? 1 : 0);
