/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VersesRouteImport } from './routes/verses'
import { Route as ApiKrishnaRouteImport } from './routes/api/krishna'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiPublicArticlesRouteImport } from './routes/api/public/articles'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicSyncArticlesRouteImport } from './routes/api/public/sync-articles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesRoute = VersesRouteImport.update({
  id: '/verses',
  path: '/verses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKrishnaRoute = ApiKrishnaRouteImport.update({
  id: '/api/krishna',
  path: '/api/krishna',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticlesRoute = ApiPublicArticlesRouteImport.update({
  id: '/api/public/articles',
  path: '/api/public/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncArticlesRoute = ApiPublicSyncArticlesRouteImport.update({
  id: '/api/public/sync-articles',
  path: '/api/public/sync-articles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/leadership': typeof LeadershipRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/quotes': typeof QuotesRoute
  '/terms': typeof TermsRoute
  '/toolkit': typeof ToolkitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verses': typeof VersesRoute
  '/api/krishna': typeof ApiKrishnaRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/sync-articles': typeof ApiPublicSyncArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/leadership': typeof LeadershipRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/quotes': typeof QuotesRoute
  '/terms': typeof TermsRoute
  '/toolkit': typeof ToolkitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verses': typeof VersesRoute
  '/api/krishna': typeof ApiKrishnaRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/sync-articles': typeof ApiPublicSyncArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/leadership': typeof LeadershipRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/quotes': typeof QuotesRoute
  '/terms': typeof TermsRoute
  '/toolkit': typeof ToolkitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verses': typeof VersesRoute
  '/api/krishna': typeof ApiKrishnaRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/sync-articles': typeof ApiPublicSyncArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/case-studies'
    | '/chat'
    | '/contact'
    | '/feedback'
    | '/leadership'
    | '/newsletter'
    | '/privacy'
    | '/quotes'
    | '/terms'
    | '/toolkit'
    | '/unsubscribe'
    | '/verses'
    | '/api/krishna'
    | '/articles/$slug'
    | '/articles/'
    | '/api/public/articles'
    | '/api/public/contact'
    | '/api/public/sync-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/case-studies'
    | '/chat'
    | '/contact'
    | '/feedback'
    | '/leadership'
    | '/newsletter'
    | '/privacy'
    | '/quotes'
    | '/terms'
    | '/toolkit'
    | '/unsubscribe'
    | '/verses'
    | '/api/krishna'
    | '/articles/$slug'
    | '/articles'
    | '/api/public/articles'
    | '/api/public/contact'
    | '/api/public/sync-articles'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/case-studies'
    | '/chat'
    | '/contact'
    | '/feedback'
    | '/leadership'
    | '/newsletter'
    | '/privacy'
    | '/quotes'
    | '/terms'
    | '/toolkit'
    | '/unsubscribe'
    | '/verses'
    | '/api/krishna'
    | '/articles/$slug'
    | '/articles/'
    | '/api/public/articles'
    | '/api/public/contact'
    | '/api/public/sync-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  FeedbackRoute: typeof FeedbackRoute
  LeadershipRoute: typeof LeadershipRoute
  NewsletterRoute: typeof NewsletterRoute
  PrivacyRoute: typeof PrivacyRoute
  QuotesRoute: typeof QuotesRoute
  TermsRoute: typeof TermsRoute
  ToolkitRoute: typeof ToolkitRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VersesRoute: typeof VersesRoute
  ApiKrishnaRoute: typeof ApiKrishnaRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ApiPublicArticlesRoute: typeof ApiPublicArticlesRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicSyncArticlesRoute: typeof ApiPublicSyncArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses': {
      id: '/verses'
      path: '/verses'
      fullPath: '/verses'
      preLoaderRoute: typeof VersesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/krishna': {
      id: '/api/krishna'
      path: '/api/krishna'
      fullPath: '/api/krishna'
      preLoaderRoute: typeof ApiKrishnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/articles': {
      id: '/api/public/articles'
      path: '/api/public/articles'
      fullPath: '/api/public/articles'
      preLoaderRoute: typeof ApiPublicArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-articles': {
      id: '/api/public/sync-articles'
      path: '/api/public/sync-articles'
      fullPath: '/api/public/sync-articles'
      preLoaderRoute: typeof ApiPublicSyncArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  FeedbackRoute: FeedbackRoute,
  LeadershipRoute: LeadershipRoute,
  NewsletterRoute: NewsletterRoute,
  PrivacyRoute: PrivacyRoute,
  QuotesRoute: QuotesRoute,
  TermsRoute: TermsRoute,
  ToolkitRoute: ToolkitRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VersesRoute: VersesRoute,
  ApiKrishnaRoute: ApiKrishnaRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ApiPublicArticlesRoute: ApiPublicArticlesRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicSyncArticlesRoute: ApiPublicSyncArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
