// AUTO-GENERATED by scripts/sync-content.mjs — do not edit by hand.
// Empty array means "no sheet configured"; src/data/gita.ts then uses its built-in verses.
import type { Verse } from "./gita";

export const syncedVerses: Verse[] = [];
